--- # Loops Playbook to create multiple users on linux nodes
- hosts: demo
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Adding Users on Linux Nodes
      action: user name='{{item}}' state=present
      with_items:
        - vivek
        - rohit
        - kunal
        - mohit
        - james
        - Alex
        - Sumit
...
